app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

Route::get('/', [
	'uses' => 'Front@index',
	'as' => 'home'
]);
Route::get('/i', [
	'uses' => 'Front@i',
	'as' => 'test'
]);
Route::get('/saludo', [
	'uses' => 'Front@saludo',
	'as' => 'saludo'
]);

Route::get('/user/{user_id}/info',[
	'uses' => 'Front@user_info',
	'as' => 'user_info'
]);

Route::get('/proyecto/{poyecto_id}',[
	'uses' => 'Front@proyecto',
	'as' => 'proyecto'
]);

Route::get('/user/{user_id}/experiencia',[
	'uses' => 'Front@user_experiencia',
	'as' => 'user_experiencia'
]);

Route::get('/user/{user_id}/publicaciones',[
	'uses' => 'Front@user_publicaciones',
	'as' => 'user_publicaciones'
]);

Route::get('/user/{user_id}/investigaciones',[
	'uses' => 'Front@user_investigaciones',
	'as' => 'user_investigaciones'
]);

Route::get('/user/{user_id}/reconocimientos',[
	'uses' => 'Front@user_reconocimientos',
	'as' => 'user_reconocimientos'
]);

/* rutas EVENTOs */
Route::get('congreso',[
	'uses' => 'Front@evento',
	'as' => 'evento'
]);

Route::get('curso',[
	'uses' => 'Front@curso',
	'as' => 'curso'
]);

Route::post('congreso',[
	'uses' => 'Participantes@registro',
	'as' => 'evento.registro'
]);
	
Route::get('confirmen',[
	'uses' => 'Front@confirmen',
	'as' =>'confirmen'
]);

/*
|--------------------------------------------------------------------------
|  RUTAS PARA VISTAS ADMINISTRATIVAS
|--------------------------------------------------------------------------
*/

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
//Route::group(['prefix'=>'admin'],function(){

	Route::get('/', [
		'uses'=>'Back@dashboard',
		'as'=>'admin.dashboard']
	);

	Route::get('/q_intereses', [
		'uses'=>'Back@intereses',
		'as'=>'intereses.query']
	);


	// rutas USUARIOS
	Route::resource('/usuarios','Usuarios',['except'=>['update','destroy']]);
	Route::post('usuarios/{user_id}',[
		'uses' =>'Usuarios@update',
		'as'=>'admin.usuarios.update']
	);
	Route::get('usuarios/{id}/destroy',[
			'uses'=>'Usuarios@destroy',
			'as' =>'admin.usuarios.destroy']
	);
	Route::post('usuaros/reordenar',[
		'uses'=>'Usuarios@reordenar',
		'as'=>'admin.usuarios.reordenar']
	);

	// rutas ASISTENTES
	Route::resource('/asistentes','Asistentes',['except'=>['update','destroy']]);
	Route::post('asistentes/{user_id}',[
		'uses' =>'Asistentes@update',
		'as'=>'admin.asistentes.update']
	);
	Route::get('asistentes/{id}/destroy',[
			'uses'=>'Asistentes@destroy',
			'as' =>'admin.asistentes.destroy']
	);
	Route::post('asistents/reordenar',[
		'uses'=>'asistentes@reordenar',
		'as'=>'admin.asistentes.reordenar']
	);


	//rutas PUBLICACIONES
	Route::resource('/publicaciones','Publicaciones',['except'=>['update','destroy']]);
	Route::post('publicaciones/{user_id}',[
		'uses' =>'Publicaciones@update',
		'as'=>'admin.publicaciones.update']
	);
	Route::get('publicaciones/{id}/destroy',[
			'uses'=>'Publicaciones@destroy',
			'as' =>'admin.publicaciones.destroy']
	);


	//rutas PONENCIAS
	Route::resource('/ponencias','Ponencias',['except'=>['update','destroy']]);
	Route::post('ponencias/{user_id}',[
		'uses' =>'Ponencias@update',
		'as'=>'admin.ponencias.update']
	);
	Route::get('ponencias/{id}/destroy',[
			'uses'=>'Ponencias@destroy',
			'as' =>'admin.ponencias.destroy']
	);

	//rutas TITULACIONES
	Route::resource('/titulaciones','Titulaciones',['except'=>['update','destroy']]);
	Route::post('titulaciones/{user_id}',[
		'uses' =>'Titulaciones@update',
		'as'=>'admin.titulaciones.update']
	);
	Route::get('titulaciones/{id}/destroy',[
			'uses'=>'Titulaciones@destroy',
			'as' =>'admin.titulaciones.destroy']
	);

	//rutas UNIVERSIDADES
	Route::resource('/universidades','Universidades',['except'=>['update','destroy']]);
	Route::post('universidades/{user_id}',[
		'uses' =>'Universidades@update',
		'as'=>'admin.universidades.update']
	);
	Route::get('universidades/{id}/destroy',[
			'uses'=>'Universidades@destroy',
			'as' =>'admin.universidades.destroy']
	);

	//rutas INTERESES
	Route::resource('/intereses','Intereses',['except'=>['update','destroy']]);
	Route::post('intereses/{user_id}',[
		'uses' =>'Intereses@update',
		'as'=>'admin.intereses.update']
	);
	Route::get('intereses/{id}/destroy',[
			'uses'=>'Intereses@destroy',
			'as' =>'admin.intereses.destroy']
	);

	//rutas TIPOS DE DOCUMENTOS
	Route::resource('/tipos_documentos','Tipos_documentos',['except'=>['update','destroy']]);
	Route::post('tipos_documentos/{user_id}',[
		'uses' =>'Tipos_documentos@update',
		'as'=>'admin.tipos_documentos.update']
	);
	Route::get('tipos_documentos/{id}/destroy',[
			'uses'=>'Tipos_documentos@destroy',
			'as' =>'admin.tipos_documentos.destroy']
	);

	//rutas DOCUMENTOS
	Route::resource('/documentos','Documentos',['except'=>['destroy']]);
	
	Route::get('documentos/{id}/destroy',[
			'uses'=>'Documentos@destroy',
			'as' =>'admin.documentos.destroy']
	);

	//rutas PROYECTOS
	Route::resource('/proyectos','Proyectos',['except'=>['update','destroy']]);
	Route::post('proyectos/{user_id}',[
		'uses' =>'Proyectos@update',
		'as'=>'admin.proyectos.update']
	);
	Route::get('proyectos/{id}/destroy',[
			'uses'=>'Proyectos@destroy',
			'as' =>'admin.proyectos.destroy']
	);


	Route::resource('/investigaciones','Investigaciones',['except'=>['update','destroy']]);
	Route::post('investigaciones/{investigacion_id}',[
		'uses' =>'Investigaciones@update',
		'as'=>'admin.investigaciones.update']
	);
	Route::get('investigaciones/{id}/destroy',[
			'uses'=>'Investigaciones@destroy',
			'as' =>'admin.investigaciones.destroy']
	);

	Route::resource('/reconocimientos','Reconocimientos',['except'=>['update','destroy']]);
	Route::post('reconocimientos/{reconocimiento_id}',[
		'uses' =>'Reconocimientos@update',
		'as'=>'admin.reconocimientos.update']
	);
	Route::get('reconocimientos/{id}/destroy',[
			'uses'=>'Reconocimientos@destroy',
			'as' =>'admin.reconocimientos.destroy']
	);
	
	Route::resource('/experiencias','Experiencias',['except'=>['update','destroy']]);
	Route::post('experiencias/{experiencia_id}',[
		'uses' =>'Experiencias@update',
		'as'=>'admin.experiencias.update']
	);
	Route::get('experiencias/{id}/destroy',[
			'uses'=>'Experiencias@destroy',
			'as' =>'admin.experiencias.destroy']
	);
	
	/* rutas IMAGENES */
	Route::get('imagenes/{id}/edit',[
		'uses' => 'Imagenes@edit',
		'as' => 'admin.imagenes.edit'
	]);
	Route::post('imagens/{id}',[
		'uses' => 'Imagenes@update',
		'as' => 'admin.imagenes.update'
	]);
	Route::post('imagenes/{canton_id}',[
		'uses' =>'Imagenes@add',
		'as'=>'admin.imagenes.store'
	]);
	Route::get('imagenes/{id}/destroy',[
		'uses'=>'Imagenes@destroy',
		'as' =>'admin.imagenes.destroy'
	]);

	/* rutas PARTICIPANTES */

	Route::resource('/participantes','Participantes',['only'=>['index','edit']]);
	Route::post('participantes/{experiencia_id}',[
		'uses' =>'Participantes@update',
		'as'=>'admin.participantes.update']
	);
	Route::get('/part/{id}','Participantes@elegir')->name('admin.participantes.elegir');
	
	Route::get('/participants/{id}','Participantes@destroy')->name('admin.participantes.destroy');

});

Route::auth();

//Route::get('/home', 'HomeController@index');

app/Http/Controllers/Back.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\User;

use App\Publicacion;
use App\Proyecto;
use App\Interes;
use App\Ponencia;

class Back extends Controller
{
	/**
     * $datos Guarda las variables que se van a pasar a la vista en un solo array
     * @var array
     */
    var $datos;

    /**
     * Constructor del controlador Front
     * aqui colocamos lo que vayamos a utilizar en todas las vistas que utiliza este controlador
     */
    public function __construct()
    {
        //setea la variable $page para agregar la clase active en el menu principal
        $this->datos['page']='dashboard';
    }


    public function dashboard(){
        $this->datos['usuarios'] = User::all();
        $this->datos['publicaciones'] = Publicacion::all();
    	$this->datos['proyectos'] = Proyecto::all();
        $this->datos['ponencias'] = Ponencia::all();
    	return view('back.dashboard',$this->datos);
    }

    public function intereses(Request $request){
        $keyword = $request->input('keyword');
        $skills = Interes::where('interes','like','%'.$keyword.'%')
                  ->select('id','interes','interes')
                  ->get();
        $skills = Interes::select('interes')->get();
        return json_encode($skills);
    }
}

resources/views/back/usuarios/create.blade.php
@extends('back.template.base')

@section('title',trans('admin.crear').' '.trans('admin.usuario'))

@section('css')
    <link rel="stylesheet" href="{{ asset('css/admin/bootstrap-datepicker3.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/libs/chosen.min.css') }}">
@endsection

@section('content')
    @include('back.template.side_menu')

<div id="page-wrapper">

    <ul class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}" title="Dashboard">Dashboard</a>
        </li>
        <li>
            <a href="{{ route('admin.usuarios.index') }}" title="{{ trans('admin.investigadores') }}">{{ trans('admin.investigadores') }}</a>
        </li>
        <li>{{ trans('admin.crear') }}</li>
    </ul>
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{{ trans('admin.usuario') }} <small>{{ trans('admin.informacion') }}</small></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>Ups! </strong> Ha ocurrido un error con tus datos.<br>
                        <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
                    <!-- content starts here -->
                    <form class="form-horizontal form-label-left" action="{{route('admin.usuarios.store')}}" method="POST" enctype="multipart/form-data" >
                    {{ csrf_field() }}
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombres">
                                {{ trans('admin.nombres') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('nombres') }}" id="nombres" name="nombres" placeholder="{{ trans('admin.nombres') }}" required="required" type="text">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellidos">
                                {{ trans('admin.apellidos') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('apellidos') }}" id="apellidos" name="apellidos" placeholder="{{ trans('admin.apellidos') }}" required="required" type="text">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="universidades">
                                {{ trans('admin.universidad') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                {!! Form::select('universidades[]',$universidades,old('universidades[]'),['required'=>'required','class'=>'form-control col-md-7 col-xs-12']) !!}
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="titulo">
                                {{ trans('admin.titulo') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('titulo') }}" id="titulo" name="titulo" placeholder="{{ trans('admin.titulo') }}" required="required" type="text">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="about_me">
                                {{ trans('admin.about_me') }}
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <textarea id="about_me" name="about_me" placeholder="{{ trans('admin.about_me') }}" class="form-control col-md-7 col-xs-12" >{{ old('about_me') }}</textarea>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="intereses">
                                {{ trans_choice('front.areas_de_interes',10) }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                {!! Form::select('intereses[]',$intereses,old('intereses[]'),['id'=>'intereses-list','multiple'=>'multiple', 'class'=>'form-control col-md-9 col-xs-9']) !!}
                                
                                <!--<input type="text" name="intereses" id='intereses-list' data-role="tagsinput"   class='form-control col-md-9 col-xs-9'>-->
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="scholar_id">
                                {{ trans('admin.scholar_id') }}
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('scholar_id') }}" id="scholar_id" name="scholar_id" placeholder="{{ trans('admin.scholar_id') }}" type="text">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">
                                {{ trans('admin.email') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('email') }}" id="email" name="email" required="required" type="email">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">
                                {{ trans('admin.telefono') }}
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('telefono') }}" id="telefono" name="telefono" type="text">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="skype">
                                {{ trans('admin.skype') }}
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" value="{{ old('skype') }}" id="skype" name="skype" type="text">
                                </input>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="imagen">
                                {{ trans('admin.imagen') }}
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                {!! Form::file('imagen',['class'=>'form-control','placeholder'=>'Imagen']) !!}
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cv">
                                CV
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                {!! Form::file('cv',['class'=>'form-control','placeholder'=>'Curriculo Vitae']) !!}
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">
                                {{ trans('admin.password') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12"  id="password" name="password" type="password" required="required"></input>
                            </div>
                        </div>
                         <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="rol">
                                {{ trans('admin.tipo') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                {!! Form::select('rol', [
                                    'docente' => trans('admin.docente'),
                                    'investigador' => trans('admin.investigador'),
                                    'tesista' => trans('admin.tesista'),
                                    'pasante' => trans('admin.pasante')
                                    ],old('rol'),[
                                        'required'=>'required',
                                        'class'=>'form-control col-md-7 col-xs-12'
                                    ]) !!}

                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">
                                {{ trans('admin.rol') }}
                                <span class="required">
                                    *
                                </span>
                            </label>
                            <div class="col-md-9 col-sm-9 col-xs-12">

                                {!! Form::select('type', [
                                    'autor' => trans('admin.autor'),
                                    'admin' => trans('admin.admin')
                                    ],old('type'),[
                                        'required'=>'required',
                                        'class'=>'form-control col-md-7 col-xs-12'
                                    ]) !!}

                            </div>
                        </div>
                        <div class="ln_solid">
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                                <a  href="{{ route('admin.usuarios.index') }}"class="btn btn-primary" >
                                    {{ trans('admin.cancelar') }}
                                </a>
                                <button class="btn btn-success" id="send" type="submit">
                                    {{ trans('admin.guardar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    <!-- content ends here -->
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>
@endsection
@section('js')
    <script src="{{ asset('js/admin/bootstrap-datepicker.min.js') }}"></script>
    
<script src="{{ asset('js/libs/chosen.jquery.min.js') }}"></script>

    <script type="text/javascript" charset="utf-8">
    $('#intereses-list').chosen({
            placeholder_text_single:"Selecciona una o varias universidades",
            width:'100%'
        });
    

</script>
@endsection

resources/views/back/usuarios/manager.blade.php
@extends('back.template.base')

@section('title',trans('admin.usuarios').' admin')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/libs/sweetalert.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery.dataTables.min.css') }}">
@endsection

@section('content')
    @include('back.template.side_menu')

<div id="page-wrapper">
    <ul class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}" title="Dashboard">Dashboard</a>
        </li>
        <li>{{ trans('admin.investigadores') }}</li>
    </ul>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        {{ trans('admin.investigadores') }}   <small> {{ trans('admin.listado') }} </small>

                        <a href="{{ route('admin.usuarios.create') }}" class="btn btn-default btn-primary">{{ trans('admin.crear') }} {{ trans('admin.investigador') }}</a>
                    </h2>
                    <div class="clearfix">
                    </div>
                </div>
                <div class="x_content">
                    <!-- content starts here -->
                    
                    <!-- start usuarios list -->
                    <table class="table table-striped projects sorted_table"  id="myTable">
                        <thead>
                            <tr>
                                <th style="width: 5%">
                                    #
                                </th>
                                <th style="width: 20%">
                                    {{ trans('admin.nombre') }}
                                </th>
                                <th>
                                    {{ trans('admin.rol') }}
                                </th>
                                <th>
                                    {{ trans('admin.universidad') }}
                                </th>
                                <th>
                                    {{ trans('admin.telefono') }}
                                </th>
                                <th style="width: 25%" class="text-center">
                                    {{ trans('admin.acciones')}}
                                </th>
                            </tr>
                        </thead>
                        <tbody >
                        	@foreach($usuarios_data as $index=>$usuar)
                            <tr id="user{{$usuar->id}}" data-user="{{$usuar->id}}">
                                <td>
                                    {{ $index+1 }} 
                                     <i class="fa fa-arrows movible"></i>
                                </td>
                                <td>
                                    <a href="{{ route('user_info',$usuar->id) }}">
                                        {{ $usuar->nombres }} {{ $usuar->apellidos }}
                                        <br/>
                                        <small>
                                            {{ $usuar->email}}
                                        </small>
                                    </a>
                                </td>
                                <td>
                                    {{ ucfirst($usuar->rol) }}
                                </td>
                                <td>
                                    @if($usuar->universidades->count()>0)
                                    {{ $usuar->universidad()->nombre }}
                                    @endif
                                    <br>
                                    <small>{{ $usuar->titulo }}</small>
                                </td>
                                <td>
                                    {{ $usuar->telefono }}
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-primary btn-xs" target="_blank" href="{{ route('user_info',$usuar->id) }}">
                                        <i class="fa fa-folder">
                                        </i>
                                        {{ trans('admin.ver') }}
                                    </a>
                                    <a class="btn btn-info btn-xs" href="{{ route('admin.usuarios.edit',$usuar->id)}}">
                                        <i class="fa fa-pencil">
                                        </i>
                                        {{ trans('admin.editar') }}
                                    </a>
                                    <a href="{{route('admin.usuarios.destroy',$usuar->id)}}" class="btn btn-danger btn-xs btn-delete">
                                        <i class="fa fa-trash-o"></i> 
                                        {{ trans('admin.eliminar') }}
                                    </a>
                                </td>
                            </tr>
                        	@endforeach
                        </tbody>
                    </table>
                    <!-- end usuarios list -->
                    <!-- content ends here -->
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
           
</div>
@endsection

@section('js')
<script src="{{ asset('js/libs/jquery-sortable-min.js') }}"></script>
<script src="{{ asset('js/libs/sweetalert.min.js') }}"></script>
<script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>

<script>
    $(document).on('click','.btn-delete',function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        swal({
          title: "{!! trans('admin.estas_seguro') !!}?",
          text: "{!! trans('admin.esta_accion_no') !!}!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "{{ trans('admin.si_eliminar') }}!",
          cancelButtonText: "{{ trans('admin.no_cancelar') }}!",
          closeOnConfirm: false,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            $.get(url,{},function(data){
                if(data.success){
                    $('#user'+data.id).fadeOut('slow');
                    swal("Eliminado!", "Eliminado correctamente", "success");
                }else{
                    swal("Error", "Error al eliminar", "error");
                }
            },'json');
          }
        });
    });
    $(document).ready(function(){
        var orden = [];
        // Sortable rows
        var group = $('.sorted_table').sortable({
                group: 'serialization',
                containerSelector: 'table',
                itemPath: '> tbody',
                itemSelector: 'tr',
                handle: 'i.fa-arrows',
                placeholder: '<tr class="placeholder"/>',
                serialize: function ($parent, $children, parentIsContainer) {
                    var result = $.extend({}, $parent.data());
                   // console.log($parent.html());
                    if($parent.data('user'))
                        orden.push({'orden':($parent.index()+1),'user':$parent.data('user')});
                },
                onDrop: function ($item, container, _super) {
                    orden = [];
                    var data = group.sortable("serialize").get();
                    $.post('{{ route("admin.usuarios.reordenar") }}',{'info':orden,_token: '{{ Session::token() }}'},function(response){
                        console.log(response);
                        console.log('response');
                        if(!response.error){
                            swal({
                                title:"OK",
                                text: "Actualizado correctamente!",
                                icon:"success",
                                buttons: false,
                                timer: 500
                            });
                        }else{
                            swal("Error", "Error al actualizar", "error");
                        }
                    });
                    _super($item, container);
                  }
            });
        });
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
</script>
@endsection