app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

Route::get('/', [
	'uses' => 'Front@index',
	'as' => 'home'
]);
Route::get('/i', [
	'uses' => 'Front@i',
	'as' => 'test'
]);
Route::get('/saludo', [
	'uses' => 'Front@saludo',
	'as' => 'saludo'
]);

Route::get('/user/{user_id}/info',[
	'uses' => 'Front@user_info',
	'as' => 'user_info'
]);

Route::get('/proyecto/{poyecto_id}',[
	'uses' => 'Front@proyecto',
	'as' => 'proyecto'
]);

Route::get('/user/{user_id}/experiencia',[
	'uses' => 'Front@user_experiencia',
	'as' => 'user_experiencia'
]);

Route::get('/user/{user_id}/publicaciones',[
	'uses' => 'Front@user_publicaciones',
	'as' => 'user_publicaciones'
]);

Route::get('/user/{user_id}/investigaciones',[
	'uses' => 'Front@user_investigaciones',
	'as' => 'user_investigaciones'
]);

Route::get('/user/{user_id}/reconocimientos',[
	'uses' => 'Front@user_reconocimientos',
	'as' => 'user_reconocimientos'
]);

/* rutas EVENTOs */
Route::get('congreso',[
	'uses' => 'Front@evento',
	'as' => 'evento'
]);

Route::get('curso',[
	'uses' => 'Front@curso',
	'as' => 'curso'
]);

Route::post('congreso',[
	'uses' => 'Participantes@registro',
	'as' => 'evento.registro'
]);
	
Route::get('confirmen',[
	'uses' => 'Front@confirmen',
	'as' =>'confirmen'
]);

/*
|--------------------------------------------------------------------------
|  RUTAS PARA VISTAS ADMINISTRATIVAS
|--------------------------------------------------------------------------
*/

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
//Route::group(['prefix'=>'admin'],function(){

	Route::get('/', [
		'uses'=>'Back@dashboard',
		'as'=>'admin.dashboard']
	);

	Route::get('/q_intereses', [
		'uses'=>'Back@intereses',
		'as'=>'intereses.query']
	);


	// rutas USUARIOS
	Route::resource('/usuarios','Usuarios',['except'=>['update','destroy']]);
	Route::post('usuarios/{user_id}',[
		'uses' =>'Usuarios@update',
		'as'=>'admin.usuarios.update']
	);
	Route::get('usuarios/{id}/destroy',[
			'uses'=>'Usuarios@destroy',
			'as' =>'admin.usuarios.destroy']
	);
	Route::post('usuaros/reordenar',[
		'uses'=>'Usuarios@reordenar',
		'as'=>'admin.usuarios.reordenar']
	);

	// rutas ASISTENTES
	Route::resource('/asistentes','Asistentes',['except'=>['update','destroy']]);
	Route::post('asistentes/{user_id}',[
		'uses' =>'Asistentes@update',
		'as'=>'admin.asistentes.update']
	);
	Route::get('asistentes/{id}/destroy',[
			'uses'=>'Asistentes@destroy',
			'as' =>'admin.asistentes.destroy']
	);
	Route::post('asistents/reordenar',[
		'uses'=>'asistentes@reordenar',
		'as'=>'admin.asistentes.reordenar']
	);


	//rutas PUBLICACIONES
	Route::resource('/publicaciones','Publicaciones',['except'=>['update','destroy']]);
	Route::post('publicaciones/{user_id}',[
		'uses' =>'Publicaciones@update',
		'as'=>'admin.publicaciones.update']
	);
	Route::get('publicaciones/{id}/destroy',[
			'uses'=>'Publicaciones@destroy',
			'as' =>'admin.publicaciones.destroy']
	);


	//rutas PONENCIAS
	Route::resource('/ponencias','Ponencias',['except'=>['update','destroy']]);
	Route::post('ponencias/{user_id}',[
		'uses' =>'Ponencias@update',
		'as'=>'admin.ponencias.update']
	);
	Route::get('ponencias/{id}/destroy',[
			'uses'=>'Ponencias@destroy',
			'as' =>'admin.ponencias.destroy']
	);

	//rutas TITULACIONES
	Route::resource('/titulaciones','Titulaciones',['except'=>['update','destroy']]);
	Route::post('titulaciones/{user_id}',[
		'uses' =>'Titulaciones@update',
		'as'=>'admin.titulaciones.update']
	);
	Route::get('titulaciones/{id}/destroy',[
			'uses'=>'Titulaciones@destroy',
			'as' =>'admin.titulaciones.destroy']
	);

	//rutas UNIVERSIDADES
	Route::resource('/universidades','Universidades',['except'=>['update','destroy']]);
	Route::post('universidades/{user_id}',[
		'uses' =>'Universidades@update',
		'as'=>'admin.universidades.update']
	);
	Route::get('universidades/{id}/destroy',[
			'uses'=>'Universidades@destroy',
			'as' =>'admin.universidades.destroy']
	);

	//rutas INTERESES
	Route::resource('/intereses','Intereses',['except'=>['update','destroy']]);
	Route::post('intereses/{user_id}',[
		'uses' =>'Intereses@update',
		'as'=>'admin.intereses.update']
	);
	Route::get('intereses/{id}/destroy',[
			'uses'=>'Intereses@destroy',
			'as' =>'admin.intereses.destroy']
	);

	//rutas TIPOS DE DOCUMENTOS
	Route::resource('/tipos_documentos','Tipos_documentos',['except'=>['update','destroy']]);
	Route::post('tipos_documentos/{user_id}',[
		'uses' =>'Tipos_documentos@update',
		'as'=>'admin.tipos_documentos.update']
	);
	Route::get('tipos_documentos/{id}/destroy',[
			'uses'=>'Tipos_documentos@destroy',
			'as' =>'admin.tipos_documentos.destroy']
	);

	//rutas DOCUMENTOS
	Route::resource('/documentos','Documentos',['except'=>['destroy']]);
	
	Route::get('documentos/{id}/destroy',[
			'uses'=>'Documentos@destroy',
			'as' =>'admin.documentos.destroy']
	);

	//rutas PROYECTOS
	Route::resource('/proyectos','Proyectos',['except'=>['update','destroy']]);
	Route::post('proyectos/{user_id}',[
		'uses' =>'Proyectos@update',
		'as'=>'admin.proyectos.update']
	);
	Route::get('proyectos/{id}/destroy',[
			'uses'=>'Proyectos@destroy',
			'as' =>'admin.proyectos.destroy']
	);


	Route::resource('/investigaciones','Investigaciones',['except'=>['update','destroy']]);
	Route::post('investigaciones/{investigacion_id}',[
		'uses' =>'Investigaciones@update',
		'as'=>'admin.investigaciones.update']
	);
	Route::get('investigaciones/{id}/destroy',[
			'uses'=>'Investigaciones@destroy',
			'as' =>'admin.investigaciones.destroy']
	);

	Route::resource('/reconocimientos','Reconocimientos',['except'=>['update','destroy']]);
	Route::post('reconocimientos/{reconocimiento_id}',[
		'uses' =>'Reconocimientos@update',
		'as'=>'admin.reconocimientos.update']
	);
	Route::get('reconocimientos/{id}/destroy',[
			'uses'=>'Reconocimientos@destroy',
			'as' =>'admin.reconocimientos.destroy']
	);
	
	Route::resource('/experiencias','Experiencias',['except'=>['update','destroy']]);
	Route::post('experiencias/{experiencia_id}',[
		'uses' =>'Experiencias@update',
		'as'=>'admin.experiencias.update']
	);
	Route::get('experiencias/{id}/destroy',[
			'uses'=>'Experiencias@destroy',
			'as' =>'admin.experiencias.destroy']
	);
	
	/* rutas IMAGENES */
	Route::get('imagenes/{id}/edit',[
		'uses' => 'Imagenes@edit',
		'as' => 'admin.imagenes.edit'
	]);
	Route::post('imagens/{id}',[
		'uses' => 'Imagenes@update',
		'as' => 'admin.imagenes.update'
	]);
	Route::post('imagenes/{canton_id}',[
		'uses' =>'Imagenes@add',
		'as'=>'admin.imagenes.store'
	]);
	Route::get('imagenes/{id}/destroy',[
		'uses'=>'Imagenes@destroy',
		'as' =>'admin.imagenes.destroy'
	]);

	/* rutas PARTICIPANTES */

	Route::resource('/participantes','Participantes',['only'=>['index','edit']]);
	Route::post('participantes/{experiencia_id}',[
		'uses' =>'Participantes@update',
		'as'=>'admin.participantes.update']
	);
	Route::get('/part/{id}','Participantes@elegir')->name('admin.participantes.elegir');
	
	Route::get('/participants/{id}','Participantes@destroy')->name('admin.participantes.destroy');

});

Route::auth();

//Route::get('/home', 'HomeController@index');

app/Http/Controllers/Back.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\User;

use App\Publicacion;
use App\Proyecto;
use App\Interes;
use App\Ponencia;

class Back extends Controller
{
	/**
     * $datos Guarda las variables que se van a pasar a la vista en un solo array
     * @var array
     */
    var $datos;

    /**
     * Constructor del controlador Front
     * aqui colocamos lo que vayamos a utilizar en todas las vistas que utiliza este controlador
     */
    public function __construct()
    {
        //setea la variable $page para agregar la clase active en el menu principal
        $this->datos['page']='dashboard';
    }


    public function dashboard(){
        $this->datos['usuarios'] = User::all();
        $this->datos['publicaciones'] = Publicacion::all();
    	$this->datos['proyectos'] = Proyecto::all();
        $this->datos['ponencias'] = Ponencia::all();
    	return view('back.dashboard',$this->datos);
    }

    public function intereses(Request $request){
        $keyword = $request->input('keyword');
        $skills = Interes::where('interes','like','%'.$keyword.'%')
                  ->select('id','interes','interes')
                  ->get();
        $skills = Interes::select('interes')->get();
        return json_encode($skills);
    }
}

app/Http/Controllers/Publicaciones.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Publicacion;
use App\User;

class Publicaciones extends Controller
{
    /**
     * $datos Guarda las variables que se van a pasar a la vista en un solo array
     * @var array
     */
    var $datos;

    /**
     * Constructor del controlador Front
     * aqui colocamos lo que vayamos a utilizar en todas las vistas que utiliza este controlador
     */
    public function __construct()
    {
        //setea la variable $page para agregar la clase active en el menu principal
        $this->datos['page']='publicaciones';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->datos['publicaciones_data'] = Publicacion::orderBy('id','ASC')->paginate(15);
        return view('back.publicaciones.manager',$this->datos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users= [];
        $usuarios = User::orderBy('nombres','ASC')->get();
        foreach ($usuarios as $key => $u) {
            $users[$u->id] = $u->nombres.' '.$u->apellidos;
        }
        $this->datos['usuarios']=$users;
        return view('back.publicaciones.create',$this->datos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $publicacion = new Publicacion($request->all());
        $publicacion->save();

        if(isset($request->usuarios)){
            $users = [];
            foreach ($request->usuarios as $key => $u) {
                $users[]=$u;
            }
            $publicacion->users()->sync($users);
        }
        //flash("$publicacion->titulo actualizado correctamente",'success');
        return redirect()->route('admin.publicaciones.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users= [];
        $usuarios = User::orderBy('nombres','ASC')->get();
        foreach ($usuarios as $key => $u) {
            $users[$u->id] = $u->nombres.' '.$u->apellidos;
        }
        $this->datos['usuarios']=$users;
        $this->datos['publicacion'] = Publicacion::find($id);
        return view('back.publicaciones.edit',$this->datos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $publicacion = Publicacion::find($id);
        $publicacion = $publicacion->fill($request->all());
        if(isset($request->usuarios)){
            $users = [];
            foreach ($request->usuarios as $key => $u) {
                $users[]=$u;
            }
            $publicacion->users()->sync($users);
        }
        $publicacion->save();

        //flash("$publicacion->titulo actualizado correctamente",'success');
        return redirect()->route('admin.publicaciones.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $usuario = Publicacion::find($id);
        $usuario->delete();
        if($request->ajax())
        {
            return response()->json(['success'=>TRUE,'id'=>$id]);
        }else{
            //flash("User $usuario->titulo eliminada correctamente",'success');
            return redirect()->route('admin.usuarios.index');
        }
    }
}

resources/views/back/publicaciones/manager.blade.php
@extends('back.template.base')

@section('title',trans('admin.publicaciones').' admin')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/jquery.dataTables.min.css') }}">
@endsection

@section('content')
    @include('back.template.side_menu')

<div id="page-wrapper">
    <ul class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}" title="Dashboard">Dashboard</a>
        </li>
        <li>{{ trans('admin.publicaciones') }}</li>
    </ul>
    <!-- /.row -->
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>
                        {{ trans('admin.publicaciones') }}   <small> {{ trans('admin.listado') }} </small>
                    </h2>
                    <div class="clearfix">
                    </div>
                </div>
                <div class="x_content">
                    <!-- content starts here -->
                    <a href="{{ route('admin.publicaciones.create') }}" class="btn btn-default btn-primary">{{ trans('admin.crear') }} {{ trans('admin.publicacion') }}</a>
                    <!-- start publicaciones list -->
                    <table class="table table-striped projects" id="myTable">
                        <thead>
                            <tr>
                                <th style="width: 5%">
                                    #
                                </th>
                                <th style="width: 20%">
                                    {{ trans('admin.nombre') }}
                                </th>
                                <th>
                                    {{ trans('admin.fecha') }}
                                </th>
                                <th>
                                    {{ trans('admin.autores') }}
                                </th>
                                <th>
                                    {{ trans('admin.citaciones') }}
                                </th>
                                <th style="width: 25%" class="text-center">
                                    {{ trans('admin.acciones')}}
                                </th>
                            </tr>
                        </thead>
                        <tbody >
                        	@foreach($publicaciones_data as $index=>$pub)
                            <tr id="user{{$pub->id}}">
                                <td>
                                    {{ $index+1 }}
                                </td>
                                <td>
                                    <a href="{{ route('admin.publicaciones.show',$pub->id) }}">
                                        {{ $pub->titulo }}
                                        <br/>
                                        <small>
                                            {{ $pub->email}}
                                        </small>
                                    </a>
                                </td>
                                <td>
                                    {{ $pub->fecha_publicacion }}
                                </td>
                                <td>
                                    @foreach($pub->users as $us)
                                        {{ $us->nombres }} {{ $us->apellidos }},
                                    @endforeach
                                </td>
                                <td>
                                    {{ $pub->citas }}
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-primary btn-xs" href="{{ route('admin.publicaciones.show',$pub->id) }}">
                                        <i class="fa fa-folder">
                                        </i>
                                        {{ trans('admin.ver') }}
                                    </a>
                                    <a class="btn btn-info btn-xs" href="{{ route('admin.publicaciones.edit',$pub->id)}}">
                                        <i class="fa fa-pencil">
                                        </i>
                                        {{ trans('admin.editar') }}
                                    </a>
                                    <a href="{{route('admin.publicaciones.destroy',$pub->id)}}" class="btn btn-danger btn-xs btn-delete">
                                        <i class="fa fa-trash-o"></i> 
                                        {{ trans('admin.eliminar') }}
                                    </a>
                                </td>
                            </tr>
                        	@endforeach
                        </tbody>
                    </table>
                    {!! $publicaciones_data->render() !!}
                    <!-- end publicaciones list -->
                    <!-- content ends here -->
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
           
</div>
@endsection

@section('js')
<script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
<script>
    $(document).on('click','.btn-delete',function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        swal({
          title: "{!! trans('admin.estas_seguro') !!}?",
          text: "{!! trans('admin.esta_accion_no') !!}!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "{{ trans('admin.si_eliminar') }}!",
          cancelButtonText: "{{ trans('admin.no_cancelar') }}!",
          closeOnConfirm: false,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            $.get(url,{},function(data){
                if(data.success){
                    $('#user'+data.id).fadeOut('slow');
                    swal("Eliminado!", "Eliminado correctamente", "success");
                }else{
                    swal("Error", "Error al eliminar", "error");
                }
            },'json');
          }
        });
    });
    $(document).ready( function () {
        $('#myTable').DataTable();
    } );
</script>
@endsection