app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

Route::get('/', [
	'uses' => 'Front@index',
	'as' => 'home'
]);
Route::get('/i', [
	'uses' => 'Front@i',
	'as' => 'test'
]);
Route::get('/saludo', [
	'uses' => 'Front@saludo',
	'as' => 'saludo'
]);

Route::get('/user/{user_id}/info',[
	'uses' => 'Front@user_info',
	'as' => 'user_info'
]);

Route::get('/proyecto/{poyecto_id}',[
	'uses' => 'Front@proyecto',
	'as' => 'proyecto'
]);

Route::get('/user/{user_id}/experiencia',[
	'uses' => 'Front@user_experiencia',
	'as' => 'user_experiencia'
]);

Route::get('/user/{user_id}/publicaciones',[
	'uses' => 'Front@user_publicaciones',
	'as' => 'user_publicaciones'
]);

Route::get('/user/{user_id}/investigaciones',[
	'uses' => 'Front@user_investigaciones',
	'as' => 'user_investigaciones'
]);

Route::get('/user/{user_id}/reconocimientos',[
	'uses' => 'Front@user_reconocimientos',
	'as' => 'user_reconocimientos'
]);

/* rutas EVENTOs */
Route::get('congreso',[
	'uses' => 'Front@evento',
	'as' => 'evento'
]);

Route::get('curso',[
	'uses' => 'Front@curso',
	'as' => 'curso'
]);

Route::post('congreso',[
	'uses' => 'Participantes@registro',
	'as' => 'evento.registro'
]);
	
Route::get('confirmen',[
	'uses' => 'Front@confirmen',
	'as' =>'confirmen'
]);

/*
|--------------------------------------------------------------------------
|  RUTAS PARA VISTAS ADMINISTRATIVAS
|--------------------------------------------------------------------------
*/

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
//Route::group(['prefix'=>'admin'],function(){

	Route::get('/', [
		'uses'=>'Back@dashboard',
		'as'=>'admin.dashboard']
	);

	Route::get('/q_intereses', [
		'uses'=>'Back@intereses',
		'as'=>'intereses.query']
	);


	// rutas USUARIOS
	Route::resource('/usuarios','Usuarios',['except'=>['update','destroy']]);
	Route::post('usuarios/{user_id}',[
		'uses' =>'Usuarios@update',
		'as'=>'admin.usuarios.update']
	);
	Route::get('usuarios/{id}/destroy',[
			'uses'=>'Usuarios@destroy',
			'as' =>'admin.usuarios.destroy']
	);
	Route::post('usuaros/reordenar',[
		'uses'=>'Usuarios@reordenar',
		'as'=>'admin.usuarios.reordenar']
	);

	// rutas ASISTENTES
	Route::resource('/asistentes','Asistentes',['except'=>['update','destroy']]);
	Route::post('asistentes/{user_id}',[
		'uses' =>'Asistentes@update',
		'as'=>'admin.asistentes.update']
	);
	Route::get('asistentes/{id}/destroy',[
			'uses'=>'Asistentes@destroy',
			'as' =>'admin.asistentes.destroy']
	);
	Route::post('asistents/reordenar',[
		'uses'=>'asistentes@reordenar',
		'as'=>'admin.asistentes.reordenar']
	);


	//rutas PUBLICACIONES
	Route::resource('/publicaciones','Publicaciones',['except'=>['update','destroy']]);
	Route::post('publicaciones/{user_id}',[
		'uses' =>'Publicaciones@update',
		'as'=>'admin.publicaciones.update']
	);
	Route::get('publicaciones/{id}/destroy',[
			'uses'=>'Publicaciones@destroy',
			'as' =>'admin.publicaciones.destroy']
	);


	//rutas PONENCIAS
	Route::resource('/ponencias','Ponencias',['except'=>['update','destroy']]);
	Route::post('ponencias/{user_id}',[
		'uses' =>'Ponencias@update',
		'as'=>'admin.ponencias.update']
	);
	Route::get('ponencias/{id}/destroy',[
			'uses'=>'Ponencias@destroy',
			'as' =>'admin.ponencias.destroy']
	);

	//rutas TITULACIONES
	Route::resource('/titulaciones','Titulaciones',['except'=>['update','destroy']]);
	Route::post('titulaciones/{user_id}',[
		'uses' =>'Titulaciones@update',
		'as'=>'admin.titulaciones.update']
	);
	Route::get('titulaciones/{id}/destroy',[
			'uses'=>'Titulaciones@destroy',
			'as' =>'admin.titulaciones.destroy']
	);

	//rutas UNIVERSIDADES
	Route::resource('/universidades','Universidades',['except'=>['update','destroy']]);
	Route::post('universidades/{user_id}',[
		'uses' =>'Universidades@update',
		'as'=>'admin.universidades.update']
	);
	Route::get('universidades/{id}/destroy',[
			'uses'=>'Universidades@destroy',
			'as' =>'admin.universidades.destroy']
	);

	//rutas INTERESES
	Route::resource('/intereses','Intereses',['except'=>['update','destroy']]);
	Route::post('intereses/{user_id}',[
		'uses' =>'Intereses@update',
		'as'=>'admin.intereses.update']
	);
	Route::get('intereses/{id}/destroy',[
			'uses'=>'Intereses@destroy',
			'as' =>'admin.intereses.destroy']
	);

	//rutas TIPOS DE DOCUMENTOS
	Route::resource('/tipos_documentos','Tipos_documentos',['except'=>['update','destroy']]);
	Route::post('tipos_documentos/{user_id}',[
		'uses' =>'Tipos_documentos@update',
		'as'=>'admin.tipos_documentos.update']
	);
	Route::get('tipos_documentos/{id}/destroy',[
			'uses'=>'Tipos_documentos@destroy',
			'as' =>'admin.tipos_documentos.destroy']
	);

	//rutas DOCUMENTOS
	Route::resource('/documentos','Documentos',['except'=>['destroy']]);
	
	Route::get('documentos/{id}/destroy',[
			'uses'=>'Documentos@destroy',
			'as' =>'admin.documentos.destroy']
	);

	//rutas PROYECTOS
	Route::resource('/proyectos','Proyectos',['except'=>['update','destroy']]);
	Route::post('proyectos/{user_id}',[
		'uses' =>'Proyectos@update',
		'as'=>'admin.proyectos.update']
	);
	Route::get('proyectos/{id}/destroy',[
			'uses'=>'Proyectos@destroy',
			'as' =>'admin.proyectos.destroy']
	);


	Route::resource('/investigaciones','Investigaciones',['except'=>['update','destroy']]);
	Route::post('investigaciones/{investigacion_id}',[
		'uses' =>'Investigaciones@update',
		'as'=>'admin.investigaciones.update']
	);
	Route::get('investigaciones/{id}/destroy',[
			'uses'=>'Investigaciones@destroy',
			'as' =>'admin.investigaciones.destroy']
	);

	Route::resource('/reconocimientos','Reconocimientos',['except'=>['update','destroy']]);
	Route::post('reconocimientos/{reconocimiento_id}',[
		'uses' =>'Reconocimientos@update',
		'as'=>'admin.reconocimientos.update']
	);
	Route::get('reconocimientos/{id}/destroy',[
			'uses'=>'Reconocimientos@destroy',
			'as' =>'admin.reconocimientos.destroy']
	);
	
	Route::resource('/experiencias','Experiencias',['except'=>['update','destroy']]);
	Route::post('experiencias/{experiencia_id}',[
		'uses' =>'Experiencias@update',
		'as'=>'admin.experiencias.update']
	);
	Route::get('experiencias/{id}/destroy',[
			'uses'=>'Experiencias@destroy',
			'as' =>'admin.experiencias.destroy']
	);
	
	/* rutas IMAGENES */
	Route::get('imagenes/{id}/edit',[
		'uses' => 'Imagenes@edit',
		'as' => 'admin.imagenes.edit'
	]);
	Route::post('imagens/{id}',[
		'uses' => 'Imagenes@update',
		'as' => 'admin.imagenes.update'
	]);
	Route::post('imagenes/{canton_id}',[
		'uses' =>'Imagenes@add',
		'as'=>'admin.imagenes.store'
	]);
	Route::get('imagenes/{id}/destroy',[
		'uses'=>'Imagenes@destroy',
		'as' =>'admin.imagenes.destroy'
	]);

	/* rutas PARTICIPANTES */

	Route::resource('/participantes','Participantes',['only'=>['index','edit']]);
	Route::post('participantes/{experiencia_id}',[
		'uses' =>'Participantes@update',
		'as'=>'admin.participantes.update']
	);
	Route::get('/part/{id}','Participantes@elegir')->name('admin.participantes.elegir');
	
	Route::get('/participants/{id}','Participantes@destroy')->name('admin.participantes.destroy');

});

Route::auth();

//Route::get('/home', 'HomeController@index');

app/Http/Controllers/Back.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\User;

use App\Publicacion;
use App\Proyecto;
use App\Interes;
use App\Ponencia;

class Back extends Controller
{
	/**
     * $datos Guarda las variables que se van a pasar a la vista en un solo array
     * @var array
     */
    var $datos;

    /**
     * Constructor del controlador Front
     * aqui colocamos lo que vayamos a utilizar en todas las vistas que utiliza este controlador
     */
    public function __construct()
    {
        //setea la variable $page para agregar la clase active en el menu principal
        $this->datos['page']='dashboard';
    }


    public function dashboard(){
        $this->datos['usuarios'] = User::all();
        $this->datos['publicaciones'] = Publicacion::all();
    	$this->datos['proyectos'] = Proyecto::all();
        $this->datos['ponencias'] = Ponencia::all();
    	return view('back.dashboard',$this->datos);
    }

    public function intereses(Request $request){
        $keyword = $request->input('keyword');
        $skills = Interes::where('interes','like','%'.$keyword.'%')
                  ->select('id','interes','interes')
                  ->get();
        $skills = Interes::select('interes')->get();
        return json_encode($skills);
    }
}

resources/views/back/template/base.blade.php
<!DOCTYPE html>
<html lang="es">
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	    <title> @yield('title') | ESPE</title>
	    <!-- Meta, title, CSS, favicons, etc. -->
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <link href="{{ asset('imagenes/icon.png')}}" rel="shortcut icon">

	    <!-- Bootstrap Core CSS -->
	    <link href="{{ asset('css/admin/bootstrap.css') }}" rel="stylesheet">

	    <!-- MetisMenu CSS -->
	    <link href="{{ asset('css/admin/metisMenu.min.css') }}" rel="stylesheet">

	    <link href="{{ asset('css/admin/sweetalert.css') }}" rel="stylesheet">

	    <!-- Custom CSS -->
	    <link href="{{ asset('css/admin/sb-admin-2.css') }}" rel="stylesheet">

	    <!-- Custom Fonts -->
	    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet" type="text/css">

	    <link rel="stylesheet" href="{{ asset('css/libs/basic.min.css') }}">
    	<link rel="stylesheet" href="{{ asset('css/libs/dropzone.min.css') }}">
    	

    	<link rel="stylesheet" href="{{ asset('css/libs/pnotify.css') }}">
    	<link rel="stylesheet" href="{{ asset('css/libs/pnotify.buttons.css') }}">

	    <link rel="shortcut icon" href="{{ asset('img/fav/favicon.ico') }}">
	    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('img/fav/apple-touch-icon-144x144.png') }}" />
	    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('img/fav/apple-touch-icon-114x114.png') }}" />
	    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('img/fav/apple-touch-icon-72x72.png') }}" />
	    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('img/fav/apple-touch-icon-57x57.png') }}" />
	    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('img/fav/apple-touch-icon-60x60.png') }}" />


	    @yield('css')
    </head>
    
	<body>
		<div id="wrapper">
			@yield('content')

		</div>
    	<!-- /#wrapper -->

		<!-- jQuery -->
		<script src="{{ asset('js/admin/jquery.min.js') }}"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="{{ asset('js/admin/bootstrap.js') }}"></script>

		<!-- Metis Menu Plugin JavaScript -->
		<script src="{{ asset('js/admin/metisMenu.min.js')}}"></script>

		<script src="{{ asset('js/libs/dropzone.min.js') }}"></script>
		
		<script src="{{ asset('js/libs/pnotify.js') }}"></script>
		<script src="{{ asset('js/libs/pnotify.buttons.js') }}"></script>

		<!-- Custom Theme JavaScript -->
		<script src="{{ asset('js/admin/sb-admin-2.js') }}"></script>
		
		<script src="{{ asset('js/admin/sweetalert.min.js') }}"></script>

	    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
	    @yield('js')
	</body>
</html>

resources/views/back/template/image_block.blade.php
<div class="col-md-4 col-lg-4 col-sm-4 col-xs-6">
    <div class="thumbnail">
        <div class="image view view-first">
            <img alt="image" src='{{ asset("img/uploads/$imagen->ruta") }}' style="width: 100%; display: block;"/>
            <div class="mask">
                <p>
                    {{ $imagen->ruta }}
                </p>
                <div class="tools tools-bottom">
                    <a href='{{ route("admin.imagenes.edit",$imagen->id) }}' class="edit-image">
                        <i class="fa fa-pencil">
                        </i>
                    </a>
                    <a href='{{ route("admin.imagenes.destroy",$imagen->id) }}' class="delete-image">
                        <i class="fa fa-times">
                        </i>
                    </a>
                </div>
            </div>
        </div>
        @if($imagen->nombre)
        <div class="caption">
            <p>
                {{ $imagen->nombre }}
            </p>
        </div>
        @endif
    </div>
</div>

resources/views/back/template/side_menu.blade.php
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
            <span class="sr-only">
                Toggle navigation
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
        </button>
        <a class="navbar-brand" href="{{ route('admin.dashboard') }}">
            Admin 
        </a>
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-tasks fa-fw">
                </i>
                <i class="fa fa-caret-down">
                </i>
            </a>
            <ul class="dropdown-menu dropdown-tasks">
                <li>
                    <a href="#">
                        <div>
                            <p>
                                <strong>
                                    Task 1
                                </strong>
                                <span class="pull-right text-muted">
                                    40% Complete
                                </span>
                            </p>
                            <div class="progress progress-striped active">
                                <div aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" class="progress-bar progress-bar-success" role="progressbar" style="width: 40%">
                                    <span class="sr-only">
                                        40% Complete (success)
                                    </span>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                <li class="divider">
                </li>
                <li>
                    <a class="text-center" href="#">
                        <strong>
                            See All Tasks
                        </strong>
                        <i class="fa fa-angle-right">
                        </i>
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-tasks -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw">
                </i>
                <i class="fa fa-caret-down">
                </i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#">
                        <i class="fa fa-user fa-fw">
                        </i>
                        User Profile
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-gear fa-fw">
                        </i>
                        Settings
                    </a>
                </li>
                <li class="divider">
                </li>
                <li>
                    <a href="{{ url('/logout') }}">
                        <i class="fa fa-sign-out fa-fw">
                        </i>
                        Logout
                    </a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input class="form-control" placeholder="Search..." type="text">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search">
                                    </i>
                                </button>
                            </span>
                        </input>
                    </div>
                    <!-- /input-group -->
                </li>
                <li>
                    <a href="{{ route('admin.dashboard') }}">
                        <i class="fa fa-dashboard fa-fw">
                        </i>
                        Dashboard
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.usuarios.index') }}">
                        <i class="fa fa-users fa-fw">
                        </i>
                        {{ trans('admin.investigadores') }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.publicaciones.index') }}">
                        <i class="fa fa-tasks fa-fw">
                        </i>
                        {{ trans('admin.publicaciones') }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.proyectos.index') }}">
                        <i class="fa fa-edit fa-fw">
                        </i>
                        {{ trans_choice('front.proyectos',10) }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.documentos.index') }}">
                        <i class="fa fa-edit fa-fw">
                        </i>
                        {{ trans_choice('front.documentos',10) }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.universidades.index') }}">
                    <i class="fa fa-users fa-fw">
                        </i>
                        {{ trans_choice('front.universidades',10) }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.ponencias.index') }}">
                    <i class="fa fa-users fa-fw">
                        </i>
                        {{ trans_choice('front.ponencias',10) }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.asistentes.index') }}">
                    <i class="fa fa-users fa-fw">
                        </i>
                        {{ trans_choice('admin.asistentes_investigadores',10) }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.titulaciones.index') }}">
                    <i class="fa fa-users fa-fw">
                        </i>
                        {{ trans_choice('admin.trabajos_titulacion',10) }}
                    </a>
                </li>

                <li></li>
                <li>
                    <a href="#">
                        <i class="fa fa-sitemap fa-fw">
                         </i>
                        Generales
                        <span class="fa arrow">
                        </span>
                     </a>
                    <ul class="nav nav-second-level">
                     <li>
                         <a href="{{ route('admin.tipos_documentos.index') }}">
                             Tipos de documentos
                         </a>
                     </li>
                     <li>
                         <a href="{{ route('admin.intereses.index') }}">
                             Intereses
                         </a>
                     </li>
                     <li>
                    <a href="{{ route('admin.participantes.index') }}">
                            {{ trans('admin.participantes') }} curso ML
                        </a>
                    </li>
                     <!--<li>
                         <a href="#">
                             Third Level
                             <span class="fa arrow">
                             </span>
                         </a>
                         <ul class="nav nav-third-level">
                             <li>
                                 <a href="#">
                                     Third Level Item
                                 </a>
                             </li>
                             <li>
                                 <a href="#">
                                     Third Level Item
                                 </a>
                             </li>
                             <li>
                                 <a href="#">
                                     Third Level Item
                                 </a>
                             </li>
                             <li>
                                 <a href="#">
                                     Third Level Item
                                 </a>
                             </li>
                         </ul>
                         <!-- /.nav-third-level 
                     </li>-->
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li></li>
                <li>
                    <a href="{{ route('home') }}" target="_blank">Ir a Front End</a>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>